# Dockerfile.fastapi
FROM python:3.9-slim

# Install necessary build tools and libraries (LAPACK, BLAS, SuiteSparse)
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    libblas-dev \
    liblapack-dev \
    libsuitesparse-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y libblas-dev liblapack-dev libsuitesparse-dev


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
